config/routes.rb
Rails.application.routes.draw do
  
  resources :kittens
  root to: "kittens#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [:show, :edit, :update, :destroy] 

  def index
    @kittens = Kitten.all
  end
  
  def show
  end

  def new
    @kitten = Kitten.new
  end

  def edit
  end

  def create
    @kitten = Kitten.create(kitten_params)
    if @kitten.save
     redirect_to @kitten, notice:"you saved a kitten!!!"
    else
      render :new, notice:"Failed to save kitten"
    end
  end

  def update
    if @kitten.update(kitten_params)
      redirect_to @kitten, notice: "You updated your kitten's info!!"
    else
      render :edit
    end
  end
 
  def destroy
    @kitten.destroy
    redirect_to root_path, notice: "Kitten was successfully removed from our database!!"
  end

  private
  def set_kitten
   @kitten = Kitten.find(params[:id])
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model:@kitten do |form|%>
  <%= form.label :name%>
  <%= form.text_field :name%><br /><br />
  <%= form.label :age%>
  <%= form.text_field :age%><br /><br />
  <%= form.label :cuteness%>
  <%= form.text_field :cuteness%><br /><br />
  <%= form.label :softness%>
  <%= form.text_field :softness%><br /><br />
  <%= form.submit%>
<% end %>

app/views/kittens/edit.html.erb
<h1>Update Kitten's info</h1>
<%= render 'form'%>

app/views/kittens/index.html.erb
<h1>Kittens</h1>

<table>
  <thead>
    <tr>
      <th>name</th>
      <th>age(days)</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kittens.each do |kitten| %>
      <tr>
        <td><%= kitten.name %></td>
        <td><%= kitten.age %></td>
        <td><%= link_to 'Show', kitten_path(kitten.id) %></td>
        <td><%= link_to 'Edit', edit_kitten_path(kitten) %></td>
        <td><%= link_to 'Destroy', kitten, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to "Create a kitten record", new_kitten_path%>

app/views/kittens/new.html.erb
<h1>Add a new kitten</h1>
<%= render 'form'%>

app/views/kittens/show.html.erb
<h1>Name: <%= @kitten.name %></h1>
<table>
  <thead>
    <tr>
     <th>age(days)</th>
     <th>cuteness</th>
     <th>softness</th>
    </tr>
  </thead>
  <tbody>
   <tr>
    <td><%= @kitten.age %></td>
    <td><%= @kitten.cuteness %></td>
    <td> <%= @kitten.softness %></td>
    </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <% if flash[:notice]%>
      <%=  notice %>
     <% end %>
    <%= yield %>
  </body>
</html>